name: parents
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.2.1
  percent_indicator: ^4.2.5
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  dio: ^5.9.0
  animations: ^2.0.11
  http: ^1.5.0
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/
